[metadata]
name = "pywal"
author = "Divinux"
origin_url = "https://github.com/Divinux/dotfiles"

[colors]
foreground = "{color15}"
background = "{background}"

cursor_fg = "{background}"
cursor_bg = "{color15}"
cursor_border = "{background}"
compose_cursor = "{color15}"

selection_fg = "{color15}"
selection_bg = "{color14}"

split = "{color14}"
scrollbar_thumb = "{color14}"
visual_bell = "{color15}"

ansi = [
    "{color0}",
    "{color1}",
    "{color2}",
    "{color3}",
    "{color4}",
    "{color5}",
    "{color6}",
    "{color7}"
]

brights = [
    "{color8}",
    "{color9}",
    "{color10}",
    "{color11}",
    "{color12}",
    "{color13}",
    "{color14}",
    "{color15}"
]

[colors.tab_bar]
background = "{color0}"
inactive_tab_edge = "{color0}"
inactive_tab_edge_hover = "{color0}"

[colors.tab_bar.active_tab]
bg_color = "{background}"
fg_color = "{color15}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "{color1}"
fg_color = "{color15}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "{color5}"
fg_color = "{background}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "{color1}"
fg_color = "{color15}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "{color5}"
fg_color = "{background}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
