name: Bashrc Tests

on:
  push:
  pull_request:

jobs:
  bats-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run tests
        run: |
          bats --verbose-run tests
